site:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

