# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.instrument_uploader:
        class: AppBundle\FileUploader
        arguments: ['%instrument_directory%']

    app.my_custom_sitemap_service:
        class: AppBundle\Iterator\SitemapIterator