# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }

    basket.twig_extension:
        class: BasketBundle\Twig\BasketExtension
        public: false
        tags:
            - { name: twig.extension }

    app.instrument_uploader:
        class: AppBundle\FileUploader
        arguments: ['%instrument_directory%']

    app.my_custom_sitemap_service:
        class: AppBundle\Iterator\SitemapIterator

    validator.unique_in_collection:
        class: AppBundle\Validator\Constraints\UniqueInCollectionValidator
        arguments:
             entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: UniqueInCollectionValidator  }
    site.tune.subscriber:
        class: SiteBundle\Subscriber\PaginateTuneSubscriber
        tags:
            - { name: knp_paginator.subscriber }
    app.form.type.fingering:
        class: AppBundle\Form\FingeringType
        tags:
            - { name: form.type }
        arguments: ['@?doctrine']
    app.listener.maintenance:
        class: AppBundle\Listener\MaintenanceListener
        arguments:
            container: "@service_container"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
